steps:
  - id: migrate
    name: 'python:3.7'
    entrypoint: 'bash'
    args: ['./migrate.sh']
    env:
      - 'CLOUD_BUILD=1'
      - 'CLOUDSQL_INSTANCE=django-example-244011:us-east1:django-example'
    waitFor: ['-"]
  - id: deploy
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--no-promote', '--version=$SHORT_SHA']
    waitFor: ['-']
  - id: promote
    name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['migrate', 'deploy']
    args: ['app', 'deploy', '--promote', '--version=$SHORT_SHA']
