steps:
  - id: migrate
    name: "python:3.7"
    entrypoint: "bash"
    args: ["./migrate.sh"]
    env: ["CLOUD_BUILD=1"]
  - id: deploy
    name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
